### ISSUE TITLE
你好，替换后脸部的高光，可以改进一下么

### ISSUE THREAD

**Issue by ljjsimon** [Jacen789/simple_faceswap#1]
如题

**Comment by Jacen789** [comment]
我新增了简单的肤色调整代码，只能一定程度的改善高光问题。如果要完全和谐掉高光的话，我还没想到该怎么做。

**Comment by aaaaaaq555555** [comment]
新增那个不删肤色代码还是跑不了，大佬

**Comment by aaaaaaq555555** [comment]
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
[ WARN:1@7.087] global D:\Build\OpenCV\opencv-4.5.5\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
这个是原报错
翻译之后是属性错误：模块 'numpy' 没有属性 'float'。
'np.float' 是内置 'float' 的弃用别名。若要避免现有代码中的此错误，请单独使用“float”。这样做不会修改任何行为，并且是安全的。如果您特别想要 numpy 标量类型，请在此处使用“np.float64”。
别名最初在 NumPy 1.20 中被弃用;有关更多详细信息和指导，请参阅原始发行说明：
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
[ WARN：1@9.807] global D：BuildOpenCVopencv-4.5.5modulesvideoiosrccap_msmf.cpp （539） 'anonymous-namespace'：：SourceReaderCB：：~SourceReaderCB 终止异步回调
