### ISSUE TITLE
请问你是否有简单的两张人脸的换脸程序

### ISSUE THREAD

**Issue by Masterzhuior** [Jacen789/simple_faceswap#2]
我不需要用到摄像头，只是想要将一张人脸换脸到另一张人脸上，这个你有操作过吗？

**Comment by Jacen789** [comment]
这个换脸程序只是简单的实现了复制粘贴的效果。对于两张脸角度不一致的情况，效果很差。这个程序可以改成不用到摄像头，如果你看得懂程序，我想这对于你来说不会太难，只需要把从摄像头读的图片写成在文件中读图片就好了。但是还是那句话，如果脸的角度不一致，效果其实不是很好。

**Comment by Masterzhuior** [comment]
好的，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jacen789/simple_faceswap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 晚上9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jacen789/simple_faceswap] 请问你是否有简单的两张人脸的换脸程序 (Issue #2)





 
这个换脸程序只是简单的实现了复制粘贴的效果。对于两张脸角度不一致的情况，效果很差。这个程序可以改成不用到摄像头，如果你看得懂程序，我想这对于你来说不会太难，只需要把从摄像头读的图片写成在文件中读图片就好了。但是还是那句话，如果脸的角度不一致，效果其实不是很好。
